### ISSUE TITLE
Air map not working

### ISSUE THREAD

**Issue by AlessandroBorges** [JunkCode/wtTactMap#108]
Hi

Seens the maps for air combat are not working anymore. 
But it does work in Naval battles.

**Comment by Button-JC** [comment]
It's working for me now (tested on Arcade BR 4.0). Do you still experience problems? On which battles rating?

PS: there is brand new version of the app here: https://play.google.com/store/apps/details?id=net.junkcode.tacticalmap ;)

**Comment by AlessandroBorges** [comment]
Please, trust me. reopen this issue.
It is not working for air combats. 
It's just froze on the first map appearance. After the first death, it updates the map but then frozen again.
Also that icon with plane for navigation mode it's not appearing.
Same issues with the new version.

**Comment by Button-JC** [comment]
I'm still unable to duplicate the issue so there is probably something specific causing this. Could you provide as many details as possible?

-  What rank and type of battles are you playing?
-  What language the War Thunder game is set to?
-  On what device the app is running and which version of Android are you using?
-  Are you running any special software that could influence the communication?

Thanks.
