### ISSUE TITLE
New version doesn't recognize Supporter / Contributor user

### ISSUE THREAD

**Issue by AlessandroBorges** [JunkCode/wtTactMap#110]
Hi, 
I'm a supporter of this application and I'd like to inform that new version doesn't recognize me as a Supporter. (Coffe/Dinner/Pizza level)

**Comment by Button-JC** [comment]
Hi,
 yes - all donations from previous app where deleted by Google and we have no access to contact information of the supporters.

If you can, forward the original receipt to the support@junkcode.net and we'll send you the manual unlock code. 
(It should look something like this:)  
![image](https://user-images.githubusercontent.com/5837140/64108613-8ce5fe80-cd7d-11e9-8154-1a0861867865.png)

**Comment by AlessandroBorges** [comment]
No problem, I just became contributor to this new one too.
