### ISSUE TITLE
Base map not visible in android app

### ISSUE THREAD

**Issue by BruceR-1** [JunkCode/wtTactMap#111]
Current version downloaded, extra ad-supported features unlocked, can display all information layers fine (grid, friendly and enemy position, etc.) except the base map on an Android phone (Nexus). When looking at it on the WT client workstation or another workstation on the same LAN, shows the base map while WT is running in Chrome at x.x.x.x:8111 or localhost:8111, although the latter sometimes shows some delay. Suggestions?

Update: Saw same issue on a Samsung Galaxy tablet. Everything is there except the base map.

**Comment by Button-JC** [comment]
Should be fixed by latest release (1.07 - currently being processed by Google Play).

**Comment by BruceR-1** [comment]
1.07 working great so far, thank you very much.

**Comment by Button-JC** [comment]
Glad to find reason for that one, thanks for reporting it :).
